// Program: radix_sort.c
// Date:    09/14/2015
// Class:   cs231
// Author:  Joel Ristvedt


/*
Description:

    This program uses a seeded number generator to get an array of integers to
sort using the radix sort. We use the issorted() function to assure that the
array is in order after the sort.

*/

#include <stdio.h>
#include <stdlib.h>
#include <math.h>


void printarray(int* array, int rows, int columns)
// Prints a given array in the specified formats (6 spaces for each)
// Parameters:
//  array - the array to print
//  rows - the number of rows in which to print the array
//  columns - the number of columns in which to print the array
{
    // print rows
    int i = 0;
    for(; i < rows; i++)
    {
        int j = 0;
        // print columns
        for(; j < columns; j++)
        {
            // i*columns = number of printed elements before THIS last for
            // loop iteration
            printf("%6d", array[(i*columns)+j]);
        }
        printf("\n");
    }
    printf("\n");
}

int issorted(int* nums, int size)
// Looks at each consecutive pair of numbers making sure the first number is
// smaller than the second
// Parameters:
//  nums - the array of numbers to be checked
//  size - the size of the array to be checked
// Return:
//  result - 0 if sorted, -1 if not sorted
{
    int i = 0, result = 0;
    while(result == 0 && i < size - 1)
    {
        if(nums[i] > nums[i+1])
        {
            result = -1;
        }
        i++;
    }
    return(result);
}



void radix_sort(int* numarray, int size)
// Sorts an array using the radix_sort approach
// Parameters:
//  numarray - the array to be sorted
//  size - the size of the array to be sorted
// Local Variables:
//  bucketarray - a single array acting as an ordered bucket
//  currentdigit - the current digit being used to sort into buckets
//  bucketindex - running index of the bucketarray
//  counter - the value at currentdigit being looked for
{
    int bucketarray[size];
    int currentdigit = 0, bucketindex = 0;

    while(currentdigit < 5)
    {
        int i = 0, counter = 0;
        for(; counter < 10; counter++)
        {
            for(i = 0; i < size; i++)
            {
                // compares the digit at currentdigit to counter
                int digitsbefore = numarray[i] / pow(10, currentdigit);
                int digit = digitsbefore % 10;
                if(digit == counter)
                {
                    bucketarray[bucketindex] = numarray[i];
                    bucketindex++;
                }
            }
        }
        // move the numbers from the bucket array to normal array
        for(i=0; i < size; i++)
        {
            numarray[i] = bucketarray[i];
        }
        currentdigit++;
        bucketindex = 0;
    }
}


int main()
// Prints instructions, recieves a numerical seed, populates an array of random
// numbers based on the seed, prints random array, checks to see if it's ordered
// orders the array using the radix sort, prints the array, and finally assures
// that the array is entirely in order.
{
    int seed = 1337;
    int randnums[500];
    const int RAND_NUMS = 500;
    const int MAX_RAND = 50000;

    printf("This program will use a radix sort to sort 500 random numbers\n");
    printf("generated by a seeded number generator. Please enter a numerical");
    printf("\nseed: ");
    scanf("%d", &seed);
    printf("\n");
    srand(seed);

    // populate randnums
    int i = 0;
    for(;i < RAND_NUMS; i++)
    {
        randnums[i] = rand() % MAX_RAND;
    }

    // print randnums
    printf("Random numbers:\n");
    printarray(randnums, 50, 10);
    if(issorted(randnums, RAND_NUMS) != 0)
    {
        printf("Numbers are NOT sorted.\n");
    }
    else printf("Numbers are sorted. You got very lucky.\n");

    // sort randnums
    printf("Sorting...\n\n");
    radix_sort(randnums, RAND_NUMS);

    // print sorted randnums
    printf("Sorted numbers:\n");
    printarray(randnums, 50, 10);
    if(issorted(randnums, RAND_NUMS) != 0)
    {
        printf("Numbers are NOT sorted.\n");
    }
    else printf("Numbers are sorted.\n");

    return(0);
}

/*

Analysis:

    This program is mostly about the radix sort so I'll evaluate that. The way
I did the radix sort added in an extra loop to loop through all the digits 
and enter them all into one big bucket rather than do one pass through and put
them each into an array. This saves space but at the cost of time. I could have
made it possible to switch which array is being looked at rather than moving
the entire contents of the bucket array to the original; not doing so added
more moves/exchanges to the sort.


*/
